on: 
  push:
    tags:
      - publish* 

defaults:
  run:
    working-directory: ./src/main/angular/widgets/

jobs:
  publish-widgets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npx npm-cli-login -u lucademmacsi -p ${{ secrets.MY_SECRET }} -e luca.demma@consulenti.csi.it -s "@lucademmacsi" -r https://npm.pkg.github.com --config-path "./.npmrc" 
      - run: cat .npmrc
      - run: npm run build:yucca-widgets
      - run: npm run build:yucca-elements
      - run: npm run publish:yucca-widgets
      - run: npm run publish:yucca-elements


