on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: ./src/main/angular/widgets/npm run build:yucca-widgets
      - run: ./src/main/angular/widgets/npm run build:yucca-elements
#      - uses: JS-DevTools/npm-publish@v1
#        with:
#          token: ${{ secrets.NPM_TOKEN }}
#          registry: https://npm.pkg.github.com/