on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: cd ./src/main/angular/widgets/ && npm install
      - run: cd ./src/main/angular/widgets/ && npm run build:yucca-widgets
      - run: cd ./src/main/angular/widgets/ && npm run build:yucca-elements
      - run: cd ./src/main/angular/widgets/ && npx npx npm-cli-login -u lucademmacsi -p ${{ secrets.MY_SECRET }} -e luca.demma@consulenti.csi.it -s "@lucademmacsi" -r https://npm.pkg.github.com